SC_CONTINUE = 100# Continue 
SC_SWITCHING_PROTOCOLS = 101# Switching Protocols 
SC_PROCESSING = 102# Processing 
SC_EARLY_HINTS = 103# Early Hints 
SC_UPLOAD_RESUMPTION_SUPPORTED = 104# Upload Resumption Supported
# 105-199 Unassigned 
SC_OK = 200 # OK 
SC_CREATED = 201 # Created 
SC_ACCEPTED = 202 # Accepted
SC_NONAUTHORATIVE_INFORMATION = 203 # Non-Authoritative Information 
SC_NO_CONTENT = 204 # No Content 
SC_RESET_CONTENT = 205 # Reset Content 
SC_PARTIAL_CONTENT = 206 # Partial Content 
SC_MULTISTATUS = 207 # Multi-Status 
SC_ALREADY_REPORTED = 208 # Already Reported 
# 209-225 Unassigned 
SC_IM_USED = 226 # IM Used 
# 227-299 Unassigned 
SC_MULTIPLE_CHOICES  = 300 # Multiple Choices 
SC_MOVED_PERMANENTLY  = 301 # Moved Permanently 
SC_FOUND  = 302 # Found 
SC_SEE_OTHER  = 303 # See Other 
SC_NOT_MODIFIED  = 304 # Not Modified 
SC_USE_PROXY  = 305 # Use Proxy 
SC_SWITCH_PROXY = 306 # Switch Proxy
SC_TEMPORARY_REDIRECT  = 307 # Temporary Redirect 
SC_PERMANENT_REDIRECT  = 308 # Permanent Redirect 
# 309-399 Unassigned 
SC_BAD_REQUEST = 400 # Bad Request
SC_UNAUTHORIZED= 401 # Unauthorized
SC_PAYMENT_REQUIRED = 402 # Payment Required
SC_FORBIDDEN = 403 # Forbidden
SC_NOT_FOUND = 404 # Not Found
SC_METHOD_NOT_ALLOWED = 405 # Method Not Allowed
SC_NOT_ACCEPTABLE = 406 # Not Acceptable
SC_PROXY_AUTHENTICATION_REQUIRED = 407 # Proxy Authentication Required
SC_REQUEST_TIMEOUT = 408 # Request Timeout
SC_CONFLICT = 409 # Conflict
SC_GONE = 410 # Gone
SC_LENGTH_REQUIRED = 411 # Length Required
SC_PRECONDITION_FAILED = 412 # Precondition Failed
SC_CONTENT_TOO_LARGE = 413 # Content Too Large
SC_URI_TOO_LONG = 414 # URI Too Long
SC_UNSUPPORTED_MEDIA_TYPE = 415 # Unsupported Media Type
SC_RANGE_NOT_SATISFIABLE = 416 # Range Not Satisfiable
SC_EXPECTATION_FAILED = 417 # Expectation Failed
# 418 (Unused)
# 419-420 Unassigned 
SC_MISDIRECTED_REQUEST = 421 #Misdirected Request
SC_UNPROCESSABLE_CONTENT = 422 #Unprocessable Content
SC_LOCKED = 423 #Locked 
SC_FAILED_DEPENDENCY = 424 #Failed Dependency 
SC_TOO_EARLY = 425 #Too Early 
SC_UPGRADE_REQUIRED = 426 #Upgrade Required
#427 Unassigned 
SC_PRECONDITION_REQUIRED = 428 #Precondition Required 
SC_TOO_MANY_REQUESTS = 429 #Too Many Requests 
# 430 Unassigned 
SC_REQUEST_HEADER_FIELDS_TOO_LARGE = 431 #Request Header Fields Too Large 
# 432-450 Unassigned 
SC_UNAVAILABLE_FOR_LEGAL_REASONS = 451 #Unavailable For Legal Reasons 
# 452-499 Unassigned 
SC_INTERNAL_SERVER_ERROR = 500 #Internal Server Error
SC_NOT_IMPLEMENTED = 501 #Not Implemented
SC_BAD_GATEWAY = 502 #Bad Gateway
SC_SERVICE_UNAVAILABLE = 503 #Service Unavailable
SC_GATEWAY_TIMEOUT = 504 #Gateway Timeout
SC_HTTP_VERSION_NOT_SUPPORTED = 505 #HTTP Version Not Supported
SC_VARIANT_ALSO_NEGOTIATES = 506 #Variant Also Negotiates 
SC_INSUFFICIENT_STORAGE = 507 #Insufficient Storage 
SC_LOOP_DETECTED = 508 #Loop Detected 
# 509 Unassigned 
SC_NOT_EXTENDED = 510 #Not Extended (OBSOLETED) 
SC_NETWORK_AUTHENTICATION_REQUIRED = 511 #Network Authentication Required 

#Aliases

CONTINUE = SC_CONTINUE
SWITCHING_PROTOCOLS = SC_SWITCHING_PROTOCOLS
PROCESSING = SC_PROCESSING
EARLY_HINTS = SC_EARLY_HINTS
UPLOAD_RESUMPTION_SUPPORTED = SC_UPLOAD_RESUMPTION_SUPPORTED
OK = SC_OK
CREATED = SC_CREATED
ACCEPTED = SC_ACCEPTED
NONAUTHORATIVE_INFORMATION = SC_NONAUTHORATIVE_INFORMATION
NO_CONTENT = SC_NO_CONTENT
RESET_CONTENT = SC_RESET_CONTENT
PARTIAL_CONTENT = SC_PARTIAL_CONTENT
MULTISTATUS = SC_MULTISTATUS
ALREADY_REPORTED = SC_ALREADY_REPORTED
IM_USED = SC_IM_USED
MULTIPLE_CHOICES  = SC_MULTIPLE_CHOICES
MOVED_PERMANENTLY  = SC_MOVED_PERMANENTLY
FOUND  = SC_FOUND
SEE_OTHER  = SC_SEE_OTHER
NOT_MODIFIED  = SC_NOT_MODIFIED
USE_PROXY  = SC_USE_PROXY
SWITCH_PROXY = SC_SWITCH_PROXY
TEMPORARY_REDIRECT  = SC_TEMPORARY_REDIRECT
PERMANENT_REDIRECT  = SC_PERMANENT_REDIRECT
BAD_REQUEST = SC_BAD_REQUEST
UNAUTHORIZED= SC_UNAUTHORIZED
PAYMENT_REQUIRED = SC_PAYMENT_REQUIRED
FORBIDDEN = SC_FORBIDDEN
NOT_FOUND = SC_NOT_FOUND
METHOD_NOT_ALLOWED = SC_METHOD_NOT_ALLOWED
NOT_ACCEPTABLE = SC_NOT_ACCEPTABLE
PROXY_AUTHENTICATION_REQUIRED = SC_PROXY_AUTHENTICATION_REQUIRED
REQUEST_TIMEOUT = SC_REQUEST_TIMEOUT
CONFLICT = SC_CONFLICT
GONE = SC_GONE
LENGTH_REQUIRED = SC_LENGTH_REQUIRED
PRECONDITION_FAILED = SC_PRECONDITION_FAILED
CONTENT_TOO_LARGE = SC_CONTENT_TOO_LARGE
URI_TOO_LONG = SC_URI_TOO_LONG
UNSUPPORTED_MEDIA_TYPE = SC_UNSUPPORTED_MEDIA_TYPE
RANGE_NOT_SATISFIABLE = SC_RANGE_NOT_SATISFIABLE
EXPECTATION_FAILED = SC_EXPECTATION_FAILED
MISDIRECTED_REQUEST = SC_MISDIRECTED_REQUEST
UNPROCESSABLE_CONTENT = SC_UNPROCESSABLE_CONTENT
LOCKED = SC_LOCKED
FAILED_DEPENDENCY = SC_FAILED_DEPENDENCY
TOO_EARLY = SC_TOO_EARLY
UPGRADE_REQUIRED = SC_UPGRADE_REQUIRED
PRECONDITION_REQUIRED = SC_PRECONDITION_REQUIRED
TOO_MANY_REQUESTS = SC_TOO_MANY_REQUESTS
REQUEST_HEADER_FIELDS_TOO_LARGE = SC_REQUEST_HEADER_FIELDS_TOO_LARGE
UNAVAILABLE_FOR_LEGAL_REASONS = SC_UNAVAILABLE_FOR_LEGAL_REASONS
INTERNAL_SERVER_ERROR = SC_INTERNAL_SERVER_ERROR
NOT_IMPLEMENTED = SC_NOT_IMPLEMENTED
BAD_GATEWAY = SC_BAD_GATEWAY
SERVICE_UNAVAILABLE = SC_SERVICE_UNAVAILABLE
GATEWAY_TIMEOUT = SC_GATEWAY_TIMEOUT
HTTP_VERSION_NOT_SUPPORTED = SC_HTTP_VERSION_NOT_SUPPORTED
VARIANT_ALSO_NEGOTIATES = SC_VARIANT_ALSO_NEGOTIATES
INSUFFICIENT_STORAGE = SC_INSUFFICIENT_STORAGE
LOOP_DETECTED = SC_LOOP_DETECTED
NOT_EXTENDED = SC_NOT_EXTENDED
NETWORK_AUTHENTICATION_REQUIRED = SC_NETWORK_AUTHENTICATION_REQUIRED


_CODE_TO_NAME = {
    100:'Continue',
    101:'Switching Protocols',
    102:'Processing',
    103:'Early Hints',
    104:'Upload Resumption Supported',
    200:'OK',
    201:'Created',
    202:'Accepted',
    203:'Non-Authoritative Information',
    204:'No Content',
    205:'Reset Content',
    206:'Partial Content',
    207:'Multi-Status',
    208:'Already Reported',
    226:'IM Used',
    300:'Multiple Choices',
    301:'Moved Permanently',
    302:'Found',
    303:'See Other',
    304:'Not Modified',
    305:'Use Proxy',
    306:'Switch Proxy',
    307:'Temporary Redirect',
    308:'Permanent Redirect',
    400:'Bad Request',
    401:'Unauthorized',
    402:'Payment Required',
    403:'Forbidden',
    404:'Not Found',
    405:'Method Not Allowed',
    406:'Not Acceptable',
    407:'Proxy Authentication Required',
    408:'Request Timeout',
    409:'Conflict',
    410:'Gone',
    411:'Length Required',
    412:'Precondition Failed',
    413:'Content Too Large',
    414:'URI Too Long',
    415:'Unsupported Media Type',
    416:'Range Not Satisfiable',
    417:'Expectation Failed',
    421:'Misdirected Request',
    422:'Unprocessable Content',
    423:'Locked',
    424:'Failed Dependency',
    425:'Too Early',
    426:'Upgrade Required',
    428:'Precondition Required',
    429:'Too Many Requests',
    431:'Request Header Fields Too Large',
    451:'Unavailable For Legal Reasons',
    500:'Internal Server Error',
    501:'Not Implemented',
    502:'Bad Gateway',
    503:'Service Unavailable',
    504:'Gateway Timeout',
    505:'HTTP Version Not Supported',
    506:'Variant Also Negotiates',
    507:'Insufficient Storage',
    508:'Loop Detected',
    510:'Not Extended',
    511:'Network Authentication Required'
}

